<?php
// Enforce (RBAC + IDOR). Determine the user's data scope (Global, Group, Personal, or None)
namespace App\Controllers;

use App\Helpers\Format;

/**
 * AKABBO SOCIAL FUND - Audit Controller
 * 
 * NOTE: The audit_logs table tracks the ACTOR (user_id) who performed the action.
 * Therefore, data scoping filters logs based on the user who generated them.
 * - Global: Sees all logs.
 * - Group: Sees logs generated by users who are members of their group.
 * - Personal: Sees only their own action logs.
 */
class AuditController extends BaseController
{
    public function __construct() 
    {
        parent::__construct();
        $this->auth->requireAuth();
    }

    // ── AUDIT LOG METHODS ──────────────────────────────────────────

    public function index(): void
    {
        // ENFORCE: Centralized Scope Gatekeeper
        $perms = [
            'global'   => 'audit.view',
            'group'    => 'groups.view_members',
            'personal' => 'members.view_own'
        ];
        $this->requireScopeAccess($perms, 'You do not have permission to view audit logs.');
        $scope = $this->resolveDataScope($perms);
        
        // ENFORCE: Scope condition applied to the actor's member_id via JOIN
        $scopeCondition = $this->buildScopeCondition($scope, 'u.member_id');

        ['page' => $page, 'limit' => $limit] = $this->getPaginationParams();
        $search = $this->getQuery('search', '');
        $module = $this->getQuery('module', '');
        $from   = $this->getQuery('from', date('Y-m-01'));
        $to     = $this->getQuery('to', date('Y-m-d'));

        $where = ['al.created_at BETWEEN ? AND ?']; 
        $params = [$from . ' 00:00:00', $to . ' 23:59:59'];
        
        if ($search) { 
            $like = "%{$search}%"; 
            $where[] = '(al.user_name LIKE ? OR al.description LIKE ? OR al.ip_address LIKE ?)'; 
            $params = array_merge($params, [$like, $like, $like]); 
        }
        if ($module) { 
            $where[] = 'al.module = ?'; 
            $params[] = $module; 
        }
        
        $ws = 'WHERE ' . implode(' AND ', $where) . " {$scopeCondition}";
        $offset = ($page - 1) * $limit;
        
        // ENFORCE: IDOR & Scope - Join with users table to map user_id (actor) to member_id
        $join = "LEFT JOIN users u ON u.id = al.user_id";
        
        $total = (int)$this->db->fetchColumn("SELECT COUNT(*) FROM audit_logs al {$join} {$ws}", $params);
        $data = $this->db->fetchAll("SELECT al.* FROM audit_logs al {$join} {$ws} ORDER BY al.id DESC LIMIT {$limit} OFFSET {$offset}", $params);
        
        // Fetch distinct modules available within the user's scope (ignoring search filters so dropdown is comprehensive)
        $scopeOnlyWs = 'WHERE 1=1 ' . $scopeCondition;
        $modules = $this->db->fetchAll("SELECT DISTINCT al.module FROM audit_logs al {$join} {$scopeOnlyWs} ORDER BY al.module");
        
        $result = [
            'data' => $data,
            'total' => $total,
            'page' => $page,
            'per_page' => $limit,
            'last_page' => (int)ceil($total / $limit),
            'from' => $total > 0 ? $offset + 1 : 0,
            'to' => min($offset + $limit, $total)
        ];
        
        $filters = compact('from', 'to', 'search', 'module');
        
        $this->view('audit/index', array_merge(
            $this->prepareViewData('Audit Log', 'audit'),
            ['result' => $result, 'modules' => $modules, 'filters' => $filters]
        ));
    }

    public function show(int $id): void
    {
        // ENFORCE: Centralized Scope Gatekeeper
        $perms = [
            'global'   => 'audit.view',
            'group'    => 'groups.view_members',
            'personal' => 'members.view_own'
        ];
        $this->requireScopeAccess($perms, 'You do not have permission to view audit logs.');
        $scope = $this->resolveDataScope($perms);
        $scopeCondition = $this->buildScopeCondition($scope, 'u.member_id');

        $join = "LEFT JOIN users u ON u.id = al.user_id";
        
        // ENFORCE: IDOR Guard - The scope condition ensures users can only view logs within their authorized tier
        $log = $this->db->fetchOne("SELECT al.* FROM audit_logs al {$join} WHERE al.id = ? {$scopeCondition}", [$id]);
        
        if (!$log) { 
            $this->flash('error', 'Audit log not found or you do not have permission to view it.'); 
            $this->redirect('/audit'); 
        }
        
        // NOTE: BaseController::view() automatically injects 'settings' and 'unreadNotifications'
        $this->view('audit/show', array_merge(
            $this->prepareViewData('Audit Entry #' . $id, 'audit', ['Audit Log' => APP_URL . '/audit', 'Entry #' . $id => null]),
            ['log' => $log]
        ));
    }
}